name: CameraBot
description: Camera neural net bot app

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  camera: ^0.10.5+5
  flutter_plugin_android_lifecycle: ^2.0.17
  image_picker: ^1.0.4
  cross_file_image: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons/AppIcons.ttf
    - family: SFProText
      fonts:
        - asset: assets/fonts/SanFranciscoProText/SFProText-Light.ttf
          weight: 300
        - asset: assets/fonts/SanFranciscoProText/SFProText-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SanFranciscoProText/SFProText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SanFranciscoProText/SFProText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SanFranciscoProText/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SanFranciscoProText/SFProText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SanFranciscoProText/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SanFranciscoProText/SFProText-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SanFranciscoProText/SFProText-Bold.ttf
          weight: 700
        - asset: assets/fonts/SanFranciscoProText/SFProText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SanFranciscoProText/SFProText-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SanFranciscoProText/SFProText-HeavyItalic.ttf
          weight: 800
          style: italic